# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afb464b5f9cf5797815abea4f11a38f411a53b878999fe98bbea7556a1de0b01559fca5186e066819c791ed4cba5fdfe7be44cdac05a9d7a7bdbcc3ff7caae96

test:
  secret_key_base: 78a6be32b9da729830bca4d8812235991754c7fefbac22d14a86ecf2aa607b4c9f63a4738bc1552887b439afa0c113bb140589e0e54814ec2549e90c2802dbb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
